name: Run Python Script to collect results

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' 

    - name: Install Dependencies and Run Script
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
        pwd && poetry run python main.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add results/
        git commit -m "Update Results"
        git push