name: Run Python Script to collect results

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' 

    - name: Install Dependencies and Run Script
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
        pwd && poetry run python main.py

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update Results"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Update Results"
        title: "Update Results"
        body: "This PR updates the results."
        branch: "update-results"