
name: Weekly Job Table Reset

on:
  schedule:
  - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  reset-db:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Reset Jobs Table
        run: |
          poetry run python -c "from internship_scraper.db import reset_jobs_table; reset_jobs_table()"