name: Collect Theses Results

on:
  schedule:
    - cron: '0 0 * * 1'  # This line schedules the workflow to run at 00:00 every Monday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' 

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Clean output directory
      run: rm output/filtered_results.csv output/results.csv output/table.md || true

    - name: Run Script
      run: |
        poetry run python main.py --job_categories "software" "cloud" "systems" --job_titles "thesis" "master thesis" --job_types " "

    - name: Move output files
      run: |
        mkdir -p output/output-theses
        mv -f output/filtered_results.csv output/output-theses/filtered_results.csv || true
        mv -f output/results.csv output/output-theses/results.csv || true
        mv -f output/table.md output/output-theses/table.md || true

    # TODO: merge from origin/main before committing
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update Results"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Update Results"
        title: "Update Theses Results"
        body: ""
        branch: "update-results-theses"
